### PR TITLE
Sensu

### PR DESCRIPTION
**Pull request by jessereynolds**
This adds Sensu. It's configured to send events to flapjack. Woo. 

Also upgrades various puppet modules we're including.

### CODE REVIEW

**Comment by jessereynolds** [comment]
I need to add some serverspec tests!
- uchiwa accessible at http://127.0.0.1:4567/
- rabbitmq admin accessible at http://127.0.0.1:15672/
- processes running: 
  - sensu-client
  - sensu-server
  - sensu-api
  - uchiwa
  - rabbitmq
  - redis (system, not flapjack)
- flapjack is receiving events from sensu (api inspect status of flapjack.example.com:check_flapper ?)

**Comment by Hobbsee** [comment]
Grabbed the latest copy of the apt module, and merged that upstream.  Looks like the following modules are new/edited:

```
rabbitmq
redis
sensu
staging
stdlib
sysctl
wget
```

**Comment by Hobbsee** [comment]
@jessereynolds Are these modules directly from the puppetlabs puppet forge, or do they need a review as well?

**Comment by jessereynolds** [comment]
@Hobbsee yep they're directly from the puppetlabs module forge, updated / installed using `puppet module update`, `puppet module install` etc.

**Comment by jessereynolds** [comment]
@Hobbsee the manifest is now pretty long and manky, it's hard to know at what point it should be split up, and how. perhaps it's ok for now.

**Comment by Hobbsee** [comment]
@jessereynolds Excellent.  This looks good - my only remaining question is - do we want to start sensu by default, or hide it behind an env variable (like the tutorial stuff?)

**Comment by Hobbsee** [comment]
> I need to add some serverspec tests!

All of these are now added.

**Comment by Hobbsee** [comment]
I think we should address the feature creep as part of a separate PR, so I'm happy for this to be merged.

**Pull request merged**
